# Generated by Django 3.0.2 on 2020-02-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uuser',
        ),
    ]
